---
  - hosts: all
    gather_facts: yes
    become: yes
    tasks:
      - name: server update
        apt:
          update_cache: yes
          state: latest

      - name: server upgrade
        apt:
          upgrade: yes
          state: latest
  - hosts: haproxy
    become: yes
    remote_user: ubuntu
    tasks:
      - name: Install HAProxy
        apt:
           name: haproxy
           state: latest

      - name: Configure HAProxy
        template:
           src: haproxy.cfg
           dest: /etc/haproxy/haproxy.cfg
        notify: restart haproxy

    handlers:
         - name: restart haproxy
           service:
                 name: haproxy
                 state: restarted

  - hosts: webservers
    remote_user: ubuntu
    become: yes
    tasks:

      - name: install python3-pip
        apt:
          name: python3-pip
          state: latest

      - name: install python3
        apt:
          name: python3
          state: latest

      - name: install flask
        pip:
          name: flask
          state: latest

      - name: create virtual environment
        shell: python3 -m venv /home/ubuntu/venv

      - name: create virtual environment directory
        file:
           path: /home/ubuntu/flask
           state: directory
           owner: ubuntu
           group: ubuntu

      - name: activate virtual environment
        become: yes
        become_user: ubuntu
        shell: . /home/ubuntu/venv/bin/activate
        args:
           chdir: /home/ubuntu/flask

      - name: copy the flask app code to the servers
        copy:
           src: app.py
           dest: /home/ubuntu/flask/app.py
           owner: ubuntu
           group: ubuntu

      - name: executing the flask-app deployment
        command: python3 app.py
        args:
           chdir: /home/ubuntu/flask
